apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: aws-lambda
  namespace: gloo-system
spec:
  aws:
    lambdaFunctions:
    - lambdaFunctionName: gloo-platform-lambda-demo
      logicalName: gloo-platform-lambda-demo
    region: us-east-2
    # this is the role you want to assume on the other account when invoking this lambda
    roleArn: arn:aws:iam::948753356872:role/ben-hack
    disableRoleChaining: false
    awsAccountId: "948753356872"
