---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-tls
  namespace: gloo-system
spec:
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: k8s-gloosyst-gatewayp-d1c525ed64-a29bd81ef3b16d96.elb.us-east-2.amazonaws.com
  dnsNames:
    - "*" 
    - "*.k8s-gloosyst-gatewayp-d1c525ed64-a29bd81ef3b16d96.elb.us-east-2.amazonaws.com"
  secretName: test-tls
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-tls
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: gateway-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /hello
      directResponseAction:
        status: 200
        body: hello, world
    - matchers:
      - prefix: /httpbin
      options:
        prefixRewrite: '/'
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
