# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: gateway
#   namespace: gloo-system
# spec:
#   isCA: true
#   secretName: gateway
#   duration: 2160h0m0s # 90d
#   renewBefore: 360h0m0s # 15d
#   commonName: gateway
#   dnsNames:
#   - '*'
#   issuerRef:
#     name: ca-issuer
#     kind: ClusterIssuer
#     group: cert-manager.io
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: sample
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /lambda-simple
      options:
        timeout: 35s  # default value is 15s
        retries:
          retryOn: '5xx'
          numRetries: 3
          perTryTimeout: '10s'
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: golang-simple-latest
              # transform request and headers to a generic map
              requestTransformation: true
          upstream:
            name: aws-lambda
            namespace: gloo-system
    - matchers:
      - exact: /hello
      directResponseAction:
        status: 200
        body: hello, world
    - matchers:
      - prefix: /httpbin
      options:
        prefixRewrite: '/'
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
    - matchers:
      - prefix: /lambda
      options:
        timeout: 35s  # default value is 15s
        retries:
          retryOn: '5xx'
          numRetries: 3
          perTryTimeout: '10s'
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: golang-echo-latest
              # this option causes headers and request info be included in body payload
              requestTransformation: true
              # wrapAsApiGateway: true
              # unwrapAsApiGateway: true
          upstream:
            name: aws-lambda
            namespace: gloo-system
    # - matchers:
    #   - prefix: /lambda
    #   options:
    #     timeout: 35s  # default value is 15s
    #     retries:
    #       retryOn: '5xx'
    #       numRetries: 3
    #       perTryTimeout: '10s'
    #   routeAction:
    #     single:
    #       destinationSpec:
    #         aws:
    #           logicalName: golang-echo-latest
    #           # this option causes headers and request info be included in body payload
    #           requestTransformation: true
    #           # wrapAsApiGateway: true
    #       upstream:
    #         name: lambda
    #         namespace: gloo-system
