---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /httpbin
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system