apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
      - name: custom-tools
        env:
        - name: "GLOO_MESH_VERSION"
          value: "v2.1.0-rc2"
