---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/meshctl
          name: custom-tools
          subPath: meshctl
        - mountPath: /var/run/gloo-scripts
          name: gloo-scripts
        - mountPath: /var/run/meshctl-values.yaml
          name: meshctl-values
          subPath: meshctl-values.yaml
        - mountPath: /var/run/gloo-license
          name: gloo-license
          readOnly: true
      initContainers:
      - name: custom-tools
        image: python:3.9.15-buster
        command:
        - "/bin/bash"
        - "/var/run/gloo-scripts/install-meshctl.sh"
        volumeMounts:
        - mountPath: /var/run/custom-tools
          name: custom-tools
        - mountPath: /var/run/gloo-scripts
          name: gloo-scripts
      volumes:
      - emptyDir: {}
        name: custom-tools
      - name: gloo-license
        secret:
          secretName: gloo-license
      - configMap:
          name: gloo-scripts
          defaultMode: 0777
        name: gloo-scripts
      - configMap:
          name: meshctl-values
        name: meshctl-values