apiVersion: networking.gloo.solo.io/v2
kind: CloudProvider
metadata:
  name: aws-provider
  namespace: app
spec:
  aws:
    stsEndpoint: sts.amazonaws.com
    accountId: "931713665590"
    region: us-east-2
    lambda:
      invokeRoleName: gloo-lambda-executor
      discovery:
        enabled: true
        # roleName: ben-gloo-discovery
