{{- $root := . }}
{{- $syncPolicy := dict  }}
{{- range $chartName, $chart := .Values.charts }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $chartName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    {{- if ($chart).repo }}
    repoURL: {{ $chart.repo }}
    {{- else }}
    repoURL: https://github.com/bdlilley/gloo-platform-argocd.git
    {{- end }}
    {{- if ($chart).revision }}
    # branch for git-hosted, chart version for helm registry-hosted
    targetRevision: {{ $chart.revision }}
    {{- else }}
    {{- if and ($chart).repo (eq $chart.repo "https://istio-release.storage.googleapis.com/charts") }}
    targetRevision: {{ $root.Values.istioVersion }}
    {{- else if and ($chart).repo (hasPrefix $chart.repo "https://storage.googleapis.com/gloo-mesh-enterprise") }}
    targetRevision: {{ $root.Values.glooVersion }}
    {{- end }}
    {{- end }}
    {{- if ($chart).path }}
    # only used for git-hosted charts
    path: {{ $chart.path }}
    {{- end }}
    {{- if ($chart).plugin }}
    plugin:
      name: {{ $chart.plugin }}
    {{- if not ($chart).path }}
    path: "."
    {{- end }}
    {{- end }}
    {{- if ($chart).chart }}
    # only used for registry-hosted charts
    chart: {{ $chart.chart }}
    {{- end }} #nd if chart.chart
{{- if and (not ($chart).plugin) ($chart).values }}
    helm:
      values: |
{{ toYaml $chart.values | indent 8 }}
{{- end }}
{{- if ($chart).repo }}
# TODO this is super hacky, need to refactor merging top level things with chart level things - 
# originally I dumped a lot of stuff in that is being blocked by charts with input validation
{{- if eq $chart.repo "https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise" }}
    helm:
      values: |
        glooGatewayLicenseKey: {{ $root.Values.glooGatewayLicenseKey }}
        glooMeshLicenseKey: {{ $root.Values.glooMeshLicenseKey }}
{{- end }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $chart.namespace }}
  syncPolicy:  {{ include "app.syncPolicy" $chart }}
{{- end }} 