{{- $root := . }}
{{- $syncPolicy := dict  }}
{{- range $chartName, $chart := .Values.charts }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $chartName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bdlilley/gloo-platform-argocd.git
    targetRevision: HEAD
    path: {{ $chart.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $chart.namespace }}
  syncPolicy:  {{ toJson(merge $root.Values.defaults.syncPolicy lookup($chart, "syncPolicy", {})) }}
  helm:
    values: | 
      istio:
        version: {{ $root.istio.version }}
{{- end }} 