{{- $root := . }}
{{- $syncPolicy := dict  }}
{{- range $chartName, $chart := .Values.charts }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $chartName }}
  namespace: argocd
spec:
  project: default
  source:
    {{- if ($chart).repo }}
    repoURL: {{ $chart.repo }}
    {{- else }}
    repoURL: https://github.com/bdlilley/gloo-platform-argocd.git
    {{- end }}
    {{- if ($chart).revision }}
    # branch for git-hosted, chart version for helm registry-hosted
    targetRevision: {{ $chart.revision }}
    {{- else }}
    targetRevision: HEAD
    {{- end }}
    {{- if ($chart).path }}
    # only used for git-hosted charts
    path: {{ $chart.path }}
    {{- end }}
    {{- if ($chart).chart }}
    # only used for registry-hosted charts
    chart: {{ $chart.chart }}
    {{- end }}
    helm:
      values: | 
        istio:
          version: {{ $root.Values.istio.version }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $chart.namespace }}
  syncPolicy:  {{ include "app.syncPolicy" $chart }}
{{- end }} 