apiVersion: networking.gloo.solo.io/v2
kind: CloudResources
metadata:
  name: aws-resources
  namespace: bookinfo
spec:
  provider: aws-provider
  lambda:
    - logicalName: aws-dest
      lambdaFunctionName: golang-gloo-latest
      qualifier: $LATEST