---
apiVersion: resilience.policy.gloo.solo.io/v2
kind: RetryTimeoutPolicy
metadata:
  name: lambda-cold-start
  namespace: istio-gateways
spec:
  applyToRoutes:
    - route:
        labels:
          route: lambda
  config:
    retries:
      attempts: 5 # optional (default is 2)
      perTryTimeout: 10s
      # retryOn specifies the conditions under which retry takes place. One or more policies can be specified using a ‘,’ delimited list.
      retryOn: "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes"
      # retryRemoteLocalities specifies whether the retries should retry to other localities, will default to false
      retryRemoteLocalities: true