apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: istio-gateway-ns
spec:
  listeners:
    - http: {}
      port:
        number: 80
  workloads:
    - selector:
        labels:
          istio: ingressgateway