---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-gateways
spec:
  secretName: tls-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
    - solo.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - '*'
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: mgmt-north-south-gw-443
  namespace: istio-gateways
spec:
  listeners:
  - http: {}
    port:
      number: 443
    tls:
      mode: SIMPLE
      secretName: tls-secret
  workloads:
  - selector:
      cluster: mgmt
      labels:
        istio: ingressgateway