---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gloo-license
  namespace: gloo-mesh
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      role: team-b
      # auth:
      #   jwt:
      #     serviceAccountRef:
      #       name: gloo-secrets-sync
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gloo-license
  namespace: gloo-mesh
spec:
  secretStoreRef:
    name: gloo-license
    kind: SecretStore
  target:
    name: gloo-mesh-license
  dataFrom:
  - extract:
      key: pm/gloo-license