{{- $root := . }}
{{- range $name, $ws := .Values.workspaces }}
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  workloadClusters:
  - name: cluster1
    namespaces: {{ toJson $root.Values.namespaces}}
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: {{ $name }}
  namespace: {{ $ws.namespace }}
spec:
{{ toYaml $ws.spec | nindent 2 }}
{{- end }}