# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: ben-gateway-cert
#   namespace: istio-gateways
# spec:
#   secretName: ben-tls-secret
#   duration: 2160h0m0s # 90d
#   renewBefore: 360h0m0s # 15d
#   subject:
#     organizations:
#     - solo.io
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   usages:
#     - server auth
#     - client auth
#   dnsNames:
#   - '*'
#   issuerRef:
#     name: selfsigned
#     kind: ClusterIssuer
#     group: cert-manager.io
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: lambda-demo-north-south-gw
  namespace: istio-gateways
spec:
  listeners:
  # - tcp: {}
  #   port:
  #     number: 30097
  #   tls:
  #     mode: SIMPLE
  #     secretName: ben-tls-secret
  - http: {}
    port:
      number: 80
    # allowedRouteTables:
    # - host: "*"
    #   selector:
    #     workspace: "app"
  workloads:
  - selector:
      cluster: mgmt
      labels:
        istio: ingressgateway