---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: gm-ui-rt-443
  namespace: gloo-mesh
spec:
  hosts:
  - '*'
  http:
  - name: lambda
    matchers:
      - uri:
          prefix: /lambda
    labels:
      route: lambda
    forwardTo:
      destinations:
        - ref:
            name: aws-provider
            namespace: istio-gateways
            cluster: mgmt
          kind: CLOUD_PROVIDER
          function:
            logicalName: golang-gloo-latest
            awsLambda:
              invocationStyle: SYNC
  # - name: gloo-mesh-ui-main
  #   labels:
  #   matchers:
  #   - uri:
  #       prefix: /welcome
  #   - uri:
  #       prefix: /login
  #   - uri:
  #       prefix: /graph
  #   - uri:
  #       prefix: /gateways
  #   - uri:
  #       prefix: /policies
  #   - uri:
  #       prefix: /static
  #   - uri:
  #       prefix: /workspace
  #   - uri:
  #       exact: /favicon.ico
  #   - uri:
  #       exact: /manifest.json
  #   - uri:
  #       regex: /rpc.gloo.solo.io.*
  #   - uri:
  #       exact: /
  #   - uri:
  #       prefix: /oidc-callback
  #   forwardTo:
  #     destinations:
  #     - ref:
  #         name: gloo-mesh-ui
  #         namespace: gloo-mesh
  #       port:
  #         number: 8090
  # - name: gmui-rewrite
  #   labels:
  #   matchers:
  #   - uri:
  #       prefix: /gmui
  #   forwardTo:
  #     pathRewrite: /
  #     destinations:
  #     - ref:
  #         name: gloo-mesh-ui
  #         namespace: gloo-mesh
  #       port:
  #         number: 8090
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []

---

# apiVersion: networking.gloo.solo.io/v2
# kind: RouteTable
# metadata:
#   labels:
#     expose: "true"
#   name: mgmt-argo-rt-443
#   namespace: argocd
# spec:
#   hosts:
#   - '*'
#   http:
#   - name: argocd
#     labels:
#       waf: "true"
#     matchers:
#     - uri:
#         prefix: /argo
#     forwardTo:
#       destinations:
#       - port:
#           number: 443
#         ref:
#           cluster: mgmt
#           name: argocd-server
#           namespace: argocd    
#   virtualGateways:
#   - cluster: mgmt
#     name: mgmt-north-south-gw-443
#     namespace: istio-gateways
#   workloadSelectors: []