charts:

  # cert-manager for issuing certs
  cert-manager:
    # wave defaults to 100
    wave: 1
    repo: https://charts.jetstack.io
    revision: v1.9.1
    chart: cert-manager
    namespace: cert-manager
    values:
      installCRDs: true

  aws-load-balancer-controller:
    wave: 1
    repo: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    revision: "1.4.5"
    namespace: kube-system
    syncPolicy:
      syncOptions: [] # dont create namespace
    values:
      # cluster name set as a global value
      replicaCount: 1
      serviceAccount:
        create: false
        name: aws-load-balancer-controller
      defaultTags:
        create-by: "benji_lilley"
        team: product
        purpose: product-development

  # external-dns to automate route53 records
  external-dns:
    # wave defaults to 100
    wave: 1
    repo: https://charts.bitnami.com/bitnami
    revision: "6.12.2"
    chart: external-dns
    namespace: kube-system
    syncPolicy:
      syncOptions: [] # dont create namespace
    values:
      domainFilters:
      - awscloud.solo.io
      crd:
        create: true
      sources:
      - crd
      aws:
        zoneType: private
      txtPrefix: extdns.
      serviceAccount:
        create: false
        name: external-dns
          
  # secrets-store-csi-driver:
  #   # wave defaults to 100
  #   wave: 1
  #   repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  #   revision: "1.3.1"
  #   chart: secrets-store-csi-driver
  #   namespace: kube-system
  #   syncPolicy:
  #     syncOptions: [] # dont create namespace
          
  core:
    wave: 10
    path: kustomize/1-core/base