charts:

  # cert-manager for issuing certs
  cert-manager:
    # wave defaults to 100
    wave: 1
    repo: https://charts.jetstack.io
    revision: v1.9.1
    chart: cert-manager
    namespace: cert-manager
    values:
      installCRDs: true

  aws-load-balancer-controller:
    wave: 1
    repo: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    revision: "1.4.5"
    namespace: kube-system
    syncPolicy:
      syncOptions: [] # dont create namespace
    values:
      # cluster name set as a global value
      replicaCount: 1
      serviceAccount:
        create: false
        name: aws-load-balancer-controller

  core:
    wave: 10
    path: kustomize/1-core/base