charts:
  k3s-core:
    wave: 10
    path: kustomize/0-core-k3s/base

  istio-base:
    wave: 20
    repo: https://istio-release.storage.googleapis.com/charts
    chart: base
    namespace: istio-system
    revision: "1.16.2"
    
  # cert-manager for issuing certs
  cert-manager:
    # wave defaults to 100
    wave: 1
    repo: https://charts.jetstack.io
    revision: v1.9.1
    chart: cert-manager
    namespace: cert-manager
    values:
      installCRDs: true
          
  # external-secrets:
  #   # wave defaults to 100
  #   wave: 1
  #   repo: https://charts.external-secrets.io
  #   revision: "0.7.2"
  #   chart: external-secrets
  #   namespace: external-secrets
          
