---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: meshctl
      generate:                      # Command to generate manifests YAML
        command: ["meshctl"]
        args: ["install", "--namespace", "gloo-mesh", "--license", "", "--chart-values-file", "", "--dry-run"]
      lockRepo: true                 # Defaults to false. See below.