---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: meshctl
      generate:                      # Command to generate manifests YAML
        command: ["/var/run/gloo-scripts/meshctl-wrapper.sh"]
        args: []
      lockRepo: true                 # Defaults to false. See below.