---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: meshctl
      # init:                          # Optional command to initialize application source directory
      #   command: ["sample command"]
      #   args: ["sample args"]
      generate:                      # Command to generate manifests YAML
        command: ["meshctl"]
        args: ["install", "--namespace", "gloo-mesh", "--license", "${GLOO_MESH_LICENSE}", "--chart-values-file", "values.yaml"]
      lockRepo: true                 # Defaults to false. See below.