---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gloo-scripts
data:
  meshctl-wrapper.sh: |
    #!/bin/bash

    LIC=$(cat /var/run/gloo-license/gloo-mesh-license-key | tr '\n' ' ')
    meshctl install --namespace gloo-mesh --license "${LIC}" --chart-values-file /var/run/meshctl-values.yaml --dry-run 

  install-meshctl.sh: |
    #!/bin/bash

    curl -sL https://run.solo.io/meshctl/install | sh -

    chmod a+rwx $HOME/.gloo-mesh/bin/meshctl
    cp $HOME/.gloo-mesh/bin/meshctl /var/run/custom-tools/meshctl

    $HOME/.gloo-mesh/bin/meshctl version
