---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gloo-scripts
data:
  meshctl-wrapper.sh: |
    #!/bin/bash

    theDir=$(mktemp -d)
    cd $theDir

    mkdir -p base
    LIC=$(cat /var/run/gloo-license/gloo-mesh-license-key | tr '\n' ' ')
    meshctl install --namespace gloo-mesh --license "${LIC}" --chart-values-file /var/run/meshctl-values.yaml --dry-run > base/meshctl.yaml

    cat <<EOF > base/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
      - meshctl.yaml
    EOF

    mkdir -p overlays/meshctl

    cat <<EOF > overlays/meshctl/meshctl/kustomization.yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    bases:
    - ../../base
    patchesStrategicMerge:
    - set-license.yaml
    EOF

    cat <<EOF > overlays/meshctl/set-license.yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: license-keys
      namespace: gloo-mesh
    data:
      gloo-mesh-license-key: "${LIC}"
      gloo-network-license-key: "${LIC}"
      gloo-gateway-license-key: "${LIC}"
      gloo-trial-license-key: "${LIC}"
    EOF

    kustomize build ./overlays/meshctl

  install-meshctl.sh: |
    #!/bin/bash

    curl -sL https://run.solo.io/meshctl/install | sh -

    chmod a+rwx $HOME/.gloo-mesh/bin/meshctl
    cp $HOME/.gloo-mesh/bin/meshctl /var/run/custom-tools/meshctl

    $HOME/.gloo-mesh/bin/meshctl version
